---

- hosts: appdbs
  become: yes
  roles:
  - db-tier

- hosts: apps
  become: yes
  roles:
  - app-tier

- hosts: frontends
  become: yes
  roles:
  - frontend

- hosts: frontends
  gather_facts: true
  tasks:
  - name: url test
    uri:
     url: "http://{{ inventory_hostname }}"
     return_content: yes
    register: output
    tags:
    - test
    failed_when: "'Tomcat' not in output.content"
  - debug:
     var: output
    tags:
    - test
